import test from "node:test";
import assert from "node:assert/strict";
import { BeadsCoordinator } from "../src/beads-coordination.js";
import { buildOwnershipMetadata, claimForCycle, runPhaseGates, startManagedCycle } from "../src/coordination-runtime.js";

test("ownership metadata carries session and cycle without changing actor semantics", () => { const m = buildOwnershipMetadata({ sessionId: "session-1", cycleId: 3, actor: "joe" }); assert.deepEqual(m, { sessionId: "session-1", cycleId: "3", actor: "joe" }); assert.throws(() => buildOwnershipMetadata({ cycleId: 1 }), /required/); });
test("claim metadata binds the lease to the current cycle", () => { const c = new BeadsCoordinator({ now: () => 1000 }); c.addIssue({ id: "i", priority: 1 }); const m = claimForCycle(c, "i", buildOwnershipMetadata({ sessionId: "s", cycleId: 1 })); assert.equal(m.issueId, "i"); assert.equal(m.sessionId, "s"); assert.equal(typeof m.leaseExpiresAt, "number"); });
test("phase gates are selected by configuration and fail closed", () => { const result = runPhaseGates({ execute: [function tests(ctx) { return ctx.phase === "execute"; }], plan: [function fail() { return false; }] }, "execute"); assert.equal(result.passed, true); assert.equal(runPhaseGates({ plan: [() => false] }, "plan").passed, false); });

test("claimed cycle checkpoints only after phase gates pass", async () => { const calls = []; const bd = { claim: async (id) => { calls.push(["claim", id]); return { sessionId: "s" }; }, checkpoint: async (id, note) => { calls.push(["checkpoint", id, note]); return { ok: true }; } }; const ok = await (await import("../src/coordination-runtime.js")).executeClaimedCycle({ bd, issueId: "i", metadata: { sessionId: "s", cycleId: "1" }, phase: "execute", gates: [() => true], evidence: "tests passed" }); assert.equal(ok.status, "checkpointed"); assert.equal(calls.length, 2); const fail = await (await import("../src/coordination-runtime.js")).executeClaimedCycle({ bd, issueId: "i", metadata: { sessionId: "s", cycleId: "2" }, phase: "execute", gates: [() => false], evidence: "not closed" }); assert.equal(fail.status, "gate_failed"); assert.equal(calls.length, 3); });

test("managed cycle result exposes ownership without issue transcript", async () => { const bd = { claim: async () => ({ expiresAt: 9 }), checkpoint: async () => ({ ok: true }) }; const result = await startManagedCycle({ bd, issueId: "i", metadata: { sessionId: "s", cycleId: "4" }, phase: "execute", gates: [() => true], evidence: "ok" }); assert.deepEqual(result.ownership, { issueId: "i", sessionId: "s", cycleId: "4" }); assert.doesNotMatch(JSON.stringify(result), /transcript|secret/); });
