import test from "node:test";
import assert from "node:assert/strict";
import { createRalphExtension } from "../src/ralph-extension.js";
test("disabled factory preserves behavior", () => { const handlers = new Map(); createRalphExtension()({ on: (n, h) => handlers.set(n, h) }); assert.equal(handlers.size, 0); });
test("enabled factory requests one safe compaction and supplies fixed result", () => { const handlers = new Map(); let compactions = 0; const pi = { on: (n, h) => handlers.set(n, h), sendMessage: () => Promise.resolve() }; createRalphExtension({ enabled: true }) (pi); handlers.get("turn_end")({ type: "turn_end", message: { role: "assistant", stopReason: "stop", content: [{ type: "text", text: "done" }] } }, { compact: () => { compactions += 1; } }); handlers.get("turn_end")({ type: "turn_end", message: { role: "assistant", stopReason: "stop", content: [{ type: "text", text: "again" }] } }, { compact: () => { compactions += 1; } }); assert.equal(compactions, 1); const result = handlers.get("session_before_compact")({ preparation: { firstKeptEntryId: "marker", tokensBefore: 4 } }); assert.equal(result.compaction.firstKeptEntryId, "marker"); assert.match(result.compaction.summary, /^RALPH_BOOTSTRAP:/); });

test("factory bounds bootstrap configuration and validates options", () => { assert.throws(() => createRalphExtension({ enabled: "yes" }), /boolean/); assert.throws(() => createRalphExtension({ goalActive: true }), /function/); const handlers = new Map(); createRalphExtension({ enabled: true, bootstrap: "x".repeat(9000) })({ on: (n, h) => handlers.set(n, h) }); const result = handlers.get("session_before_compact")({ preparation: { firstKeptEntryId: "m", tokensBefore: 1 } }); assert.ok(result.compaction.summary.length < 4100); });

test("factory rejects unsupported Prime Agent versions when supplied", () => { assert.throws(() => createRalphExtension({ primeAgentVersion: "0.9.0" }), /unsupported/); assert.doesNotThrow(() => createRalphExtension({ primeAgentVersion: "0.8.0" })); });
